version: 1.0.0.{build}

environment:
  configuration: Release

branches:
  except:
  - design

image: Visual Studio 2017

install:
- ps: |
- cmd: echo '%APPVEYOR_REPO_COMMIT_MESSAGE%' > commit.txt 

cache:
- '%USERPROFILE%\.nuget\packages -> **\*.csproj'

before_build:
- ps: |
    appveyor-retry dotnet restore
    $path = (Get-Item .\src\PeopleLookup.Mvc\PeopleLookup.Mvc.csproj).FullName
    $csproj = [xml](Get-Content $path)
    $csproj.Project.PropertyGroup.Version = $Env:APPVEYOR_BUILD_VERSION
    $csproj.Save($path)
build_script:
- cmd: msbuild .\src\PeopleLookup.Mvc.csproj /t:Publish /p:Configuration=%configuration%
- cmd: msbuild /t:Build /p:Configuration=%configuration%;PackageVersion=%APPVEYOR_BUILD_VERSION%
